import json
import sqlite3
from pathlib import Path
from typing import Any

from langchain_core.documents import Document

from config import OLIST_DB_PATH
from vectorstore import olist_schema_store


# =========================================================
# Human-defined semantic metadata
# =========================================================
#
# These are NOT generated by the LLM.
# They are part of our governed schema knowledge.
# =========================================================

TABLE_METADATA = {
    "orders": {
        "purpose": (
            "Order-level information. One row represents one Olist order "
            "and contains order status and lifecycle timestamps."
        ),
        "grain": "One row per order.",
        "primary_key": ["order_id"],
    },

    "order_items": {
        "purpose": (
            "Item-level order information. Each row represents one product "
            "item within an order, including seller, price, freight, and "
            "shipping deadline."
        ),
        "grain": "One row per item within an order.",
        "primary_key": ["order_id", "order_item_id"],
    },

    "order_payments": {
        "purpose": (
            "Payment-level information for orders. An order may have multiple "
            "payment entries."
        ),
        "grain": "One row per payment entry associated with an order.",
        "primary_key": ["order_id", "payment_sequential"],
    },

    "order_reviews": {
        "purpose": (
            "Customer review information associated with orders, including "
            "review score, text, and review timestamps."
        ),
        "grain": "One row per review record.",
        "primary_key": ["review_id"],
    },

    "customers": {
        "purpose": (
            "Customer information associated with Olist orders, including "
            "order-level customer ID and the persistent unique customer ID."
        ),
        "grain": "One row per order/customer relationship.",
        "primary_key": ["customer_id"],
    },

    "products": {
        "purpose": (
            "Product master data containing category and physical product "
            "attributes."
        ),
        "grain": "One row per product.",
        "primary_key": ["product_id"],
    },

    "sellers": {
        "purpose": (
            "Seller master data including seller identifier and seller "
            "location."
        ),
        "grain": "One row per seller.",
        "primary_key": ["seller_id"],
    },

    "geolocation": {
        "purpose": (
            "Brazilian geographic reference data connecting ZIP-code prefixes "
            "to latitude, longitude, city, and state."
        ),
        "grain": "Multiple geographic records may exist for a ZIP-code prefix.",
        "primary_key": [],
    },

    "product_category_name_translation": {
        "purpose": (
            "Mapping from Portuguese Olist product category names to English "
            "category names."
        ),
        "grain": "One row per translated category.",
        "primary_key": ["product_category_name"],
    },
}


# =========================================================
# Explicit relationship knowledge
# =========================================================

RELATIONSHIPS = {
    "orders": [
        "orders.customer_id -> customers.customer_id (many orders-to-one customer record)",
        "orders.order_id -> order_items.order_id (one order-to-many order items)",
        "orders.order_id -> order_payments.order_id (one order-to-many payment entries)",
        "orders.order_id -> order_reviews.order_id (order-to-review relationship)",
    ],
    "order_items": [
        "order_items.order_id -> orders.order_id (many-to-one)",
        "order_items.product_id -> products.product_id (many-to-one)",
        "order_items.seller_id -> sellers.seller_id (many-to-one)",
    ],
    "order_payments": [
        "order_payments.order_id -> orders.order_id (many-to-one)",
    ],
    "order_reviews": [
        "order_reviews.order_id -> orders.order_id",
    ],
    "customers": [
        "customers.customer_id <- orders.customer_id",
        "customers.customer_unique_id identifies the underlying customer across orders",
    ],
    "products": [
        "products.product_id <- order_items.product_id",
        "products.product_category_name -> product_category_name_translation.product_category_name",
    ],
    "sellers": [
        "sellers.seller_id <- order_items.seller_id",
    ],
    "geolocation": [
        "geolocation.geolocation_zip_code_prefix can relate to customers.customer_zip_code_prefix",
        "geolocation.geolocation_zip_code_prefix can relate to sellers.seller_zip_code_prefix",
    ],
    "product_category_name_translation": [
        "product_category_name_translation.product_category_name <- products.product_category_name",
    ],
}


# =========================================================
# Semantic / analytical rules
# =========================================================

SEMANTIC_RULES = {
    "orders": [
        "order_id uniquely identifies an order.",
        "order_purchase_timestamp is the canonical purchase date/time for sales-period analysis.",
        "order_status describes the order lifecycle state.",
        "For the current benchmark definition, canonical sales/GMV uses delivered orders unless a question explicitly requests another population.",
    ],

    "order_items": [
        "COUNT(*) on order_items counts item rows, not orders.",
        "COUNT(DISTINCT order_id) should be used when counting orders from order_items.",
        "price is the canonical item-level sales value used for GMV.",
        "freight_value is freight and is separate from canonical GMV.",
        "An order may contain multiple order_items.",
        "Different items within the same order may belong to different sellers.",
    ],

    "order_payments": [
        "An order can have multiple payment rows.",
        "payment_value is payment-level value, not the canonical GMV metric.",
        "Aggregate payments to order grain before joining to item-level data when analyzing order payments together with order items.",
        "Directly joining raw order_payments to order_items can create fan-out and inflate sums.",
    ],

    "order_reviews": [
        "Reviews should not be blindly joined to order_items because this can multiply item rows.",
    ],

    "customers": [
        "customer_id identifies the customer record associated with an order.",
        "customer_unique_id identifies the underlying customer across orders.",
        "For unique customer counts, use COUNT(DISTINCT customer_unique_id).",
        "COUNT(DISTINCT customer_id) is not equivalent to unique customer count.",
    ],

    "products": [
        "product_category_name is the original Portuguese category name.",
        "Use product_category_name_translation to obtain the English category name.",
        "610 product records have NULL product_category_name in this database.",
    ],

    "geolocation": [
        "geolocation is not guaranteed to be one row per ZIP-code prefix.",
        "Do not assume geolocation_zip_code_prefix is a unique key.",
    ],

    "product_category_name_translation": [
        "This table is a lookup from Portuguese category names to English category names.",
    ],
}


# =========================================================
# Utility functions
# =========================================================

def quote_identifier(name: str) -> str:
    """Safely quote a SQLite identifier."""
    return '"' + name.replace('"', '""') + '"'


def get_tables(conn: sqlite3.Connection) -> list[str]:
    rows = conn.execute(
        """
        SELECT name
        FROM sqlite_master
        WHERE type = 'table'
          AND name NOT LIKE 'sqlite_%'
        ORDER BY name
        """
    ).fetchall()

    return [row[0] for row in rows]


def get_columns(
    conn: sqlite3.Connection,
    table: str,
) -> list[dict[str, Any]]:
    rows = conn.execute(
        f"PRAGMA table_info({quote_identifier(table)})"
    ).fetchall()

    columns = []

    for row in rows:
        columns.append(
            {
                "cid": row[0],
                "name": row[1],
                "type": row[2] or "UNKNOWN",
                "notnull": bool(row[3]),
                "default": row[4],
                "pk": row[5],
            }
        )

    return columns


def get_row_count(conn: sqlite3.Connection, table: str) -> int:
    return conn.execute(
        f"SELECT COUNT(*) FROM {quote_identifier(table)}"
    ).fetchone()[0]


def get_distinct_count(
    conn: sqlite3.Connection,
    table: str,
    column: str,
) -> int:
    return conn.execute(
        f"""
        SELECT COUNT(DISTINCT {quote_identifier(column)})
        FROM {quote_identifier(table)}
        """
    ).fetchone()[0]


def get_null_count(
    conn: sqlite3.Connection,
    table: str,
    column: str,
) -> int:
    return conn.execute(
        f"""
        SELECT COUNT(*)
        FROM {quote_identifier(table)}
        WHERE {quote_identifier(column)} IS NULL
        """
    ).fetchone()[0]


def is_numeric_type(sql_type: str) -> bool:
    sql_type = sql_type.upper()

    return any(
        token in sql_type
        for token in (
            "INT",
            "REAL",
            "NUM",
            "DECIMAL",
            "FLOAT",
            "DOUBLE",
        )
    )


def is_date_column(column_name: str) -> bool:
    name = column_name.lower()

    return any(
        token in name
        for token in (
            "timestamp",
            "date",
        )
    )


def get_numeric_stats(
    conn: sqlite3.Connection,
    table: str,
    column: str,
) -> dict[str, Any]:
    row = conn.execute(
        f"""
        SELECT
            MIN({quote_identifier(column)}),
            MAX({quote_identifier(column)}),
            AVG({quote_identifier(column)})
        FROM {quote_identifier(table)}
        WHERE {quote_identifier(column)} IS NOT NULL
        """
    ).fetchone()

    return {
        "min": row[0],
        "max": row[1],
        "avg": row[2],
    }


def get_top_values(
    conn: sqlite3.Connection,
    table: str,
    column: str,
    limit: int = 10,
) -> list[tuple[Any, int]]:
    return conn.execute(
        f"""
        SELECT
            {quote_identifier(column)},
            COUNT(*) AS cnt
        FROM {quote_identifier(table)}
        WHERE {quote_identifier(column)} IS NOT NULL
        GROUP BY {quote_identifier(column)}
        ORDER BY cnt DESC
        LIMIT {limit}
        """
    ).fetchall()


def get_sample_values(
    conn: sqlite3.Connection,
    table: str,
    column: str,
    limit: int = 8,
) -> list[Any]:
    rows = conn.execute(
        f"""
        SELECT DISTINCT {quote_identifier(column)}
        FROM {quote_identifier(table)}
        WHERE {quote_identifier(column)} IS NOT NULL
        LIMIT {limit}
        """
    ).fetchall()

    return [row[0] for row in rows]


def get_sample_rows(
    conn: sqlite3.Connection,
    table: str,
    limit: int = 5,
) -> tuple[list[str], list[tuple[Any, ...]]]:
    columns = [
        row[1]
        for row in conn.execute(
            f"PRAGMA table_info({quote_identifier(table)})"
        ).fetchall()
    ]

    rows = conn.execute(
        f"""
        SELECT *
        FROM {quote_identifier(table)}
        LIMIT {limit}
        """
    ).fetchall()

    return columns, rows


def format_value(value: Any) -> str:
    if value is None:
        return "NULL"

    text = str(value)

    # Keep documents readable.
    text = text.replace("\n", " ")
    text = text.replace("\r", " ")

    if len(text) > 150:
        text = text[:147] + "..."

    return text


# =========================================================
# Document construction
# =========================================================

def build_table_document(
    conn: sqlite3.Connection,
    table: str,
) -> Document:

    metadata = TABLE_METADATA.get(
        table,
        {
            "purpose": "Olist dataset table.",
            "grain": "Unknown.",
            "primary_key": [],
        },
    )

    columns = get_columns(conn, table)
    row_count = get_row_count(conn, table)

    sections: list[str] = []

    # -----------------------------------------------------
    # Table overview
    # -----------------------------------------------------

    sections.append(
        f"""
TABLE: {table}

PURPOSE:
{metadata["purpose"]}

GRAIN:
{metadata["grain"]}

ROW COUNT:
{row_count:,}

PRIMARY KEY / UNIQUE KEY:
{", ".join(metadata["primary_key"]) if metadata["primary_key"] else "No reliable single primary key is defined."}
""".strip()
    )

    # -----------------------------------------------------
    # Column details
    # -----------------------------------------------------

    column_lines = ["COLUMNS:"]

    for column in columns:
        name = column["name"]
        sql_type = column["type"]
        null_count = get_null_count(conn, table, name)
        distinct_count = get_distinct_count(conn, table, name)

        line = (
            f"\n{name}\n"
            f"  data_type: {sql_type}\n"
            f"  nullable: {'yes' if null_count > 0 else 'no'}\n"
            f"  null_count: {null_count:,}\n"
            f"  distinct_count: {distinct_count:,}"
        )

        # Primary-key marker
        if column["pk"]:
            line += "\n  declared_primary_key: yes"

        # Numeric/date statistics
        if is_numeric_type(sql_type):
            stats = get_numeric_stats(conn, table, name)

            line += (
                f"\n  min: {format_value(stats['min'])}"
                f"\n  max: {format_value(stats['max'])}"
                f"\n  average: {format_value(stats['avg'])}"
            )

        # Date range / examples
        if is_date_column(name):
            stats = get_numeric_stats(conn, table, name)

            line += (
                f"\n  observed_min: {format_value(stats['min'])}"
                f"\n  observed_max: {format_value(stats['max'])}"
            )

        # Top values for likely categorical/text columns
        if sql_type.upper() in ("TEXT", "VARCHAR", "CHAR", ""):
            top_values = get_top_values(conn, table, name, limit=8)

            if top_values:
                formatted = ", ".join(
                    f"{format_value(value)} ({count})"
                    for value, count in top_values
                )

                line += f"\n  top_values: {formatted}"

                examples = get_sample_values(
                    conn,
                    table,
                    name,
                    limit=5,
                )

                if examples:
                    line += (
                        "\n  example_values: "
                        + ", ".join(format_value(v) for v in examples)
                    )

        column_lines.append(line)

    sections.append("\n".join(column_lines))

    # -----------------------------------------------------
    # Relationships
    # -----------------------------------------------------

    relationships = RELATIONSHIPS.get(table, [])

    if relationships:
        sections.append(
            "RELATIONSHIPS:\n"
            + "\n".join(f"- {r}" for r in relationships)
        )

    # -----------------------------------------------------
    # Semantic rules
    # -----------------------------------------------------

    rules = SEMANTIC_RULES.get(table, [])

    if rules:
        sections.append(
            "SEMANTIC / ANALYTICAL RULES:\n"
            + "\n".join(f"- {r}" for r in rules)
        )

    # -----------------------------------------------------
    # Example rows
    # -----------------------------------------------------

    sample_columns, sample_rows = get_sample_rows(
        conn,
        table,
        limit=5,
    )

    row_lines = [
        "EXAMPLE ROWS:",
        " | ".join(sample_columns),
    ]

    for row in sample_rows:
        row_lines.append(
            " | ".join(format_value(value) for value in row)
        )

    sections.append("\n".join(row_lines))

    # -----------------------------------------------------
    # Final document
    # -----------------------------------------------------

    page_content = "\n\n".join(sections)

    return Document(
        page_content=page_content,
        metadata={
            "dataset": "olist",
            "doc_type": "table_schema",
            "table": table,
            "grain": metadata["grain"],
            "row_count": row_count,
        },
    )


# =========================================================
# Main
# =========================================================

def main() -> None:
    if not OLIST_DB_PATH.exists():
        raise FileNotFoundError(
            f"Olist database not found: {OLIST_DB_PATH}"
        )

    conn = sqlite3.connect(OLIST_DB_PATH)

    try:
        tables = get_tables(conn)

        print("Tables found:")
        for table in tables:
            print(f"  - {table}")

        docs = []

        for index, table in enumerate(tables, start=1):
            print(
                f"\n[{index}/{len(tables)}] Building document: {table}"
            )

            doc = build_table_document(
                conn,
                table,
            )

            docs.append(doc)

            print(
                f"  characters: {len(doc.page_content):,}"
            )

        print(
            f"\nPrepared {len(docs)} Olist table documents."
        )

        # Add in batches.
        batch_size = 3

        for start in range(0, len(docs), batch_size):
            batch = docs[start:start + batch_size]

            print(
                f"Embedding documents "
                f"{start + 1}-{min(start + batch_size, len(docs))}"
            )

            olist_schema_store.add_documents(batch)

        print(
            "\n✅ Olist schema documents embedded successfully."
        )

    finally:
        conn.close()


if __name__ == "__main__":
    main()